[package]
name = "enjo"
description = "Projects management tool."
authors = ["Konstantin Zhigaylo <zero@kostyazero.com>"]
repository = "https://github.com/kostya-zero/enjo"
keywords = ["workspace"]
readme = "README.md"
license = "MIT"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "4.5.1"
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.4.2"

[profile.release]
lto = "thin"
opt-level = 3
