[package]
name = "enjo"
description = "Minimalist workspace assistant."
authors = [ "Konstantin Zhigaylo <zero@kostyazero.com>" ]
homepage = "https://github.com/kostya-zero/enjo"
keywords = ["workspace"]
readme = "README.md"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.18"
home = "0.5.9"
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"
enjo_configs = { version = "0.1.0", path = "./crates/enjo_configs" }
enjo_tools = { version = "0.1.0", path = "./crates/enjo_tools" }

[profile.release]
lto = "thin"
opt-level = 2
codegen-units = 1

[workspace]
members = [
    "crates/enjo_configs", 
    "crates/enjo_tools"
]
resolver = "2"

