[package]
name = "enjo"
description = "Projects management tool."
authors = ["Konstantin Zhigaylo <zero@kostyazero.com>"]
repository = "https://github.com/kostya-zero/enjo"
keywords = ["workspace"]
readme = "README.md"
license = "MIT"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = "4.5.1"
dialoguer = "0.11.0"
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.61"
toml = "0.8.10"

[dev-dependencies]
tempfile = "3.10.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.4.2"

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = false
