[package]
name = "vel"
description = "Minimalist projects manager."
authors = [ "Konstantin Zhigaylo <kostya.zero@outlook.com>" ]
version = "0.1.0-dev"
edition = "2021"


[dependencies]
clap = "4.4.4"
home = "0.5.5"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.0"
