name: Run Clippy

on:
  push

jobs:
  clippy:
    runs-on: docker
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy
        run: cargo clippy -- -Dwarnings


